# Pytrends - Google Trends API

Using Pytrends to get keywords data from Google Trends

Source: https://www.premiumleads.com/en/blog/seo/how-to-get-google-trends-data-with-pytrends-and-python/

Geoloaction Dataset: https://www.kaggle.com/datasets/paultimothymooney/latitude-and-longitude-for-every-country-and-state?select=world_country_and_usa_states_latitude_and_longitude_values.csv

Documentation Page: https://pypi.org/project/pytrends/

By Lee-Ann Moore

In [1]:
#Install Pytrends
!pip install pytrends

Requirement already satisfied: pytrends in c:\python anaconda\lib\site-packages (4.8.0)
Requirement already satisfied: requests>=2.0 in c:\python anaconda\lib\site-packages (from pytrends) (2.27.1)
Requirement already satisfied: lxml in c:\python anaconda\lib\site-packages (from pytrends) (4.6.3)
Requirement already satisfied: pandas>=0.25 in c:\python anaconda\lib\site-packages (from pytrends) (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\python anaconda\lib\site-packages (from pandas>=0.25->pytrends) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\python anaconda\lib\site-packages (from pandas>=0.25->pytrends) (1.20.1)
Requirement already satisfied: pytz>=2017.3 in c:\python anaconda\lib\site-packages (from pandas>=0.25->pytrends) (2021.1)
Requirement already satisfied: six>=1.5 in c:\python anaconda\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.25->pytrends) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python anaconda\lib\site-packages (from requests>=2.0->pytrends) (2020.12.5)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\python anaconda\lib\site-packages (from requests>=2.0->pytrends) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\python anaconda\lib\site-packages (from requests>=2.0->pytrends) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python anaconda\lib\site-packages (from requests>=2.0->pytrends) (1.26.4)

In [2]:
#Import pandas and TrendReq from pytrends
import pandas as pd                        
from pytrends.request import TrendReq
pytrends = TrendReq(hl='en-US')

# Weekly Interest Over Time for Keywords 

Notes: Pytrends only allows 5 keywords at a time. This is weekly data from 12 months ago.

In [3]:
#Create a list of keywords related to the fintech industry and called that variable 'keyword'
keyword = ["investment management","personal finance", "virtual cards", "digital wallet", "financial planning"]

#Print the Interest Over Time for the keyword list and called that variable 'keyword_interest'
pytrends.build_payload(keyword, cat=0, timeframe="today 12-m", geo="US")
keyword_interest = pytrends.interest_over_time()
keyword_interest

,investment management,personal finance,virtual cards,digital wallet,financial planning,isPartial
date,,,,,,
2021-04-11,78,81,21,30,81,False
2021-04-18,83,82,19,30,83,False
2021-04-25,77,86,18,21,91,False
2021-05-02,80,79,28,32,85,False
2021-05-09,71,83,23,31,78,False
2021-05-16,76,67,19,25,77,False
2021-05-23,69,66,14,23,73,False
2021-05-30,63,66,14,28,72,False
2021-06-06,84,58,18,31,66,False
2021-06-13,76,65,17,28,65,False
2021-06-20,72,55,15,23,66,False
2021-06-27,74,53,14,28,59,False
2021-07-04,65,55,16,20,64,False
2021-07-11,69,58,16,29,73,False
2021-07-18,74,59,17,24,67,False
2021-07-25,72,66,17,22,65,False
2021-08-01,67,60,17,32,64,False
2021-08-08,74,65,11,27,64,False
2021-08-15,65,66,16,28,58,False
2021-08-22,69,75,19,31,65,False
2021-08-29,82,93,16,26,80,False
2021-09-05,71,73,19,26,77,False
2021-09-12,79,69,17,27,81,False
2021-09-19,88,72,15,21,80,False
2021-09-26,74,74,18,29,89,False
2021-10-03,85,75,19,28,73,False
2021-10-10,80,73,20,25,86,False
2021-10-17,100,76,20,28,81,False
2021-10-24,81,67,21,41,89,False
2021-10-31,85,73,19,31,80,False
2021-11-07,79,76,20,44,84,False
2021-11-14,78,81,18,34,78,False
2021-11-21,63,57,20,36,62,False
2021-11-28,83,86,22,29,85,False
2021-12-05,81,78,22,25,76,False
2021-12-12,66,70,33,31,68,False
2021-12-19,56,58,46,39,48,False
2021-12-26,40,64,23,28,57,False
2022-01-02,63,81,19,25,69,False
2022-01-09,70,95,20,27,75,False
2022-01-16,75,69,16,23,68,False
2022-01-23,84,86,19,26,83,False
2022-01-30,86,79,21,24,66,False
2022-02-06,79,80,23,26,72,False
2022-02-13,78,72,23,23,80,False
2022-02-20,79,71,18,27,74,False
2022-02-27,84,70,19,24,76,False
2022-03-06,86,68,19,32,83,False
2022-03-13,70,66,17,23,70,False
2022-03-20,78,85,16,26,79,False
2022-03-27,82,90,19,27,91,False
2022-04-03,48,73,13,29,70,True

# Hourly Historical Interest Over Time for Keywords 

Notes: Pytrends API provides hourly data. This data is focused on keyword interest from January 1, 2022 to March 31, 2022. 
This will be used for forcasting data.

In [4]:
#Print the hourly historical interst of the keywords for Q1 2022
kw_hist_interest = pytrends.get_historical_interest(keyword, year_start=2022, month_start=1, day_start=1, hour_start=0, year_end=2022, month_end=3, day_end=31, hour_end=0, cat=0, geo='US', gprop='', sleep=0)
kw_hist_interest

,investment management,personal finance,virtual cards,digital wallet,financial planning,isPartial
date,,,,,,
2022-01-01 00:00:00,0,5,5,10,10,False
2022-01-01 01:00:00,5,5,0,10,5,False
2022-01-01 02:00:00,0,5,5,0,5,False
2022-01-01 03:00:00,6,6,5,0,5,False
2022-01-01 04:00:00,6,6,6,0,0,False
...,...,...,...,...,...,...
2022-03-30 20:00:00,45,26,5,8,33,False
2022-03-30 21:00:00,30,20,6,6,23,False
2022-03-30 22:00:00,26,21,6,6,20,False
2022-03-30 23:00:00,23,18,6,7,20,False
2022-03-31 00:00:00,21,15,9,7,12,False

# Interest By Region (United States) for Keywords 

Notes: Pytrends API provides keyword interest by region. For this section, the data will be focused on the United States and which states are interested in certain keywords.

In [5]:
# Print the Interest by Region(United States) and called the variable 'keyword_region'
keyword_region = pytrends.interest_by_region(resolution='REGION', inc_low_vol=True, inc_geo_code=False)
keyword_region

,investment management,personal finance,virtual cards,digital wallet,financial planning
geoName,,,,,
Alabama,22,29,8,10,31
Alaska,0,100,0,0,0
Arizona,21,31,7,14,27
Arkansas,24,35,7,9,25
California,30,24,7,12,27
Colorado,29,29,7,11,24
Connecticut,44,20,4,8,24
Delaware,33,32,6,4,25
District of Columbia,46,20,6,9,19
Florida,26,24,7,9,34
Georgia,23,37,7,9,24
Hawaii,28,25,6,9,32
Idaho,26,39,4,0,31
Illinois,31,23,5,7,34
Indiana,21,36,6,10,27
Iowa,21,28,5,8,38
Kansas,20,33,6,5,36
Kentucky,20,36,10,9,25
Louisiana,21,31,11,11,26
Maine,25,47,4,0,24
Maryland,25,28,9,10,28
Massachusetts,46,21,3,6,24
Michigan,26,32,8,7,27
Minnesota,29,28,6,7,30
Mississippi,20,35,7,5,33
Missouri,27,35,6,8,24
Montana,25,48,0,0,27
Nebraska,19,41,5,8,27
Nevada,21,31,13,11,24
New Hampshire,28,41,6,0,25
New Jersey,39,24,6,7,24
New Mexico,19,26,7,10,38
New York,42,16,3,5,34
North Carolina,31,26,6,9,28
North Dakota,27,44,9,0,20
Ohio,24,27,6,7,36
Oklahoma,15,39,8,11,27
Oregon,21,32,8,12,27
Pennsylvania,30,28,8,9,25
Rhode Island,34,27,5,0,34
South Carolina,21,32,7,11,29
South Dakota,0,55,10,0,35
Tennessee,17,42,6,7,28
Texas,26,29,6,10,29
Utah,21,37,9,9,24
Vermont,30,29,5,0,36
Virginia,27,35,6,7,25
Washington,23,35,7,10,25
West Virginia,20,39,8,9,24
Wisconsin,27,27,4,8,34
Wyoming,0,74,0,0,26

In [6]:
#Read the geolocation dataset and name it 'lat_lon'
lat_lon = pd.read_csv('world_country_and_usa_states_latitude_and_longitude_values.csv')
lat_lon.head()

  usa_state_code  usa_state_latitude  usa_state_longitude   usa_state
0             AK           63.588753          -154.493062      Alaska
1             AL           32.318231           -86.902298     Alabama
2             AR           35.201050           -91.831833    Arkansas
3             AZ           34.048928          -111.093731     Arizona
4             CA           36.778261          -119.417932  California

In [7]:
#Rename the usa_name column to geoName to match the keyword_region data and preview the data
lat_lon.rename(columns = {'usa_state':'geoName'}, inplace = True)
lat_lon.head()

  usa_state_code  usa_state_latitude  usa_state_longitude     geoName
0             AK           63.588753          -154.493062      Alaska
1             AL           32.318231           -86.902298     Alabama
2             AR           35.201050           -91.831833    Arkansas
3             AZ           34.048928          -111.093731     Arizona
4             CA           36.778261          -119.417932  California

In [8]:
#Merge the lat_lon dataframe with the keyword_region dataframe on the left "geoName" column
merged_kw_region = lat_lon.merge(keyword_region, how='left', on="geoName")
merged_kw_region

,usa_state_code,usa_state_latitude,usa_state_longitude,geoName,investment management,personal finance,virtual cards,digital wallet,financial planning
0,AK,63.588753,-154.493062,Alaska,0.0,100.0,0.0,0.0,0.0
1,AL,32.318231,-86.902298,Alabama,22.0,29.0,8.0,10.0,31.0
2,AR,35.201050,-91.831833,Arkansas,24.0,35.0,7.0,9.0,25.0
3,AZ,34.048928,-111.093731,Arizona,21.0,31.0,7.0,14.0,27.0
4,CA,36.778261,-119.417932,California,30.0,24.0,7.0,12.0,27.0
5,CO,39.550051,-105.782067,Colorado,29.0,29.0,7.0,11.0,24.0
6,CT,41.603221,-73.087749,Connecticut,44.0,20.0,4.0,8.0,24.0
7,DC,38.905985,-77.033418,District of Columbia,46.0,20.0,6.0,9.0,19.0
8,DE,38.910832,-75.527670,Delaware,33.0,32.0,6.0,4.0,25.0
9,FL,27.664827,-81.515754,Florida,26.0,24.0,7.0,9.0,34.0
10,GA,32.157435,-82.907123,Georgia,23.0,37.0,7.0,9.0,24.0
11,HI,19.898682,-155.665857,Hawaii,28.0,25.0,6.0,9.0,32.0
12,IA,41.878003,-93.097702,Iowa,21.0,28.0,5.0,8.0,38.0
13,ID,44.068202,-114.742041,Idaho,26.0,39.0,4.0,0.0,31.0
14,IL,40.633125,-89.398528,Illinois,31.0,23.0,5.0,7.0,34.0
15,IN,40.551217,-85.602364,Indiana,21.0,36.0,6.0,10.0,27.0
16,KS,39.011902,-98.484246,Kansas,20.0,33.0,6.0,5.0,36.0
17,KY,37.839333,-84.270018,Kentucky,20.0,36.0,10.0,9.0,25.0
18,LA,31.244823,-92.145024,Louisiana,21.0,31.0,11.0,11.0,26.0
19,MA,42.407211,-71.382437,Massachusetts,46.0,21.0,3.0,6.0,24.0
20,MD,39.045755,-76.641271,Maryland,25.0,28.0,9.0,10.0,28.0
21,ME,45.253783,-69.445469,Maine,25.0,47.0,4.0,0.0,24.0
22,MI,44.314844,-85.602364,Michigan,26.0,32.0,8.0,7.0,27.0
23,MN,46.729553,-94.685900,Minnesota,29.0,28.0,6.0,7.0,30.0
24,MO,37.964253,-91.831833,Missouri,27.0,35.0,6.0,8.0,24.0
25,MS,32.354668,-89.398528,Mississippi,20.0,35.0,7.0,5.0,33.0
26,MT,46.879682,-110.362566,Montana,25.0,48.0,0.0,0.0,27.0
27,NC,35.759573,-79.019300,North Carolina,31.0,26.0,6.0,9.0,28.0
28,ND,47.551493,-101.002012,North Dakota,27.0,44.0,9.0,0.0,20.0
29,NE,41.492537,-99.901813,Nebraska,19.0,41.0,5.0,8.0,27.0
30,NH,43.193852,-71.572395,New Hampshire,28.0,41.0,6.0,0.0,25.0
31,NJ,40.058324,-74.405661,New Jersey,39.0,24.0,6.0,7.0,24.0
32,NM,34.972730,-105.032363,New Mexico,19.0,26.0,7.0,10.0,38.0
33,NV,38.802610,-116.419389,Nevada,21.0,31.0,13.0,11.0,24.0
34,NY,43.299428,-74.217933,New York,42.0,16.0,3.0,5.0,34.0
35,OH,40.417287,-82.907123,Ohio,24.0,27.0,6.0,7.0,36.0
36,OK,35.007752,-97.092877,Oklahoma,15.0,39.0,8.0,11.0,27.0
37,OR,43.804133,-120.554201,Oregon,21.0,32.0,8.0,12.0,27.0
38,PA,41.203322,-77.194525,Pennsylvania,30.0,28.0,8.0,9.0,25.0
39,PR,18.220833,-66.590149,Puerto Rico,NaN,NaN,NaN,NaN,NaN
40,RI,41.580095,-71.477429,Rhode Island,34.0,27.0,5.0,0.0,34.0
41,SC,33.836081,-81.163725,South Carolina,21.0,32.0,7.0,11.0,29.0
42,SD,43.969515,-99.901813,South Dakota,0.0,55.0,10.0,0.0,35.0
43,TN,35.517491,-86.580447,Tennessee,17.0,42.0,6.0,7.0,28.0
44,TX,31.968599,-99.901813,Texas,26.0,29.0,6.0,10.0,29.0
45,UT,39.320980,-111.093731,Utah,21.0,37.0,9.0,9.0,24.0
46,VA,37.431573,-78.656894,Virginia,27.0,35.0,6.0,7.0,25.0
47,VT,44.558803,-72.577841,Vermont,30.0,29.0,5.0,0.0,36.0
48,WA,47.751074,-120.740139,Washington,23.0,35.0,7.0,10.0,25.0
49,WI,43.784440,-88.787868,Wisconsin,27.0,27.0,4.0,8.0,34.0
50,WV,38.597626,-80.454903,West Virginia,20.0,39.0,8.0,9.0,24.0
51,WY,43.075968,-107.290284,Wyoming,0.0,74.0,0.0,0.0,26.0

# Top 20 Related Queries 

Notes: Pytrends API provides related queries that could help content teams create content related to the keywords.

In [9]:
#Print the related queries for the keyword list
pytrends.related_queries()

{'investment management': {'top':                                    query  value
  0          investment management company    100
  1          what is investment management     74
  2                       asset management     63
  3           wealth investment management     55
  4                      wealth management     55
  5             investment management fees     52
  6             investment management firm     44
  7                        investment bank     41
  8      real estate investment management     41
  9                   return on investment     37
  10                      money management     37
  11                   property management     33
  12            investment risk management     33
  13        investment property management     30
  14       investment management companies     30
  15                  investment companies     29
  16            investment management jobs     26
  17                    investment advisor     26
  18        investment management services     26
  19  morgan stanley investment management     18
  20         elliott investment management     18
  21                  portfolio management     15
  22      investment management mba online     15
  23                        morgan stanley     15
  24       investment portfolio management     15,
  'rising':                                                 query   value
  0                    investment management mba online  146350
  1                 institutional investment management  109700
  2                            k1 investment management  109600
  3                         orbis investment management   73150
  4                        summit investment management   73100
  5   in which situation would a savings bond be the...   73100
  6                                  investment service   73100
  7                                                iapd   73100
  8             monarch investment and management group   73050
  9                      manulife investment management   73050
  10                  norges bank investment management   73000
  11  where do banks get money to lend to borrowers?...   73000
  12                     goldman sachs asset management   72150
  13  what is the best reason for jacinta to have a ...   36500
  14                          srs investment management   36500
  15       financial intermediary investment management   36500
  16                                    ares management   36500
  17                   prudential investment management   36500
  18                          abs investment management   36500
  19                       kingswood capital management   36500
  20  what is one benefit of purchasing saving bonds...   36500
  21                               fidelity investments   36500
  22                    schroders investment management   36450
  23  which of these is an advantage of checking acc...   36450
  24                    voloridge investment management   36450},
 'personal finance': {'top':                           query  value
  0      what is personal finance    100
  1       reddit personal finance     91
  2                 personal loan     88
  3                          loan     88
  4         personal loan finance     88
  5                personal loans     62
  6        personal finance loans     62
  7                         money     56
  8      personal finance quizlet     47
  9          personal finance app     38
  10    personal finance software     24
  11  personal finance management     24
  12      personal finance budget     23
  13     personal finance company     21
  14        personal finance book     21
  15   personal finance education     21
  16        personal finance jobs     21
  17      personal finance course     18
  18                yahoo finance     18
  19       yahoo personal finance     18
  20                world finance     18
  21         personal finance lab     18
  22        personal finance apps     18
  23              mariner finance     18
  24    personal finance planning     17,
  'rising':                                                 query  value
  0                        personal finance for dummies  92600
  1                              personal loans near me  92600
  2                                       loans near me  91750
  3                                    republic finance  61700
  4                             personal finance advice  61700
  5                          kiplinger personal finance  61150
  6                                    possible finance  61150
  7                              personal finance tools  61150
  8                               personal finance blog  30800
  9                      best books on personal finance  30800
  10                           nextgen personal finance  30800
  11  planning to finance higher education helps peo...  30800
  12  planning to finance higher education helps peo...  30800
  13                                  reddit retirement  30750
  14                  5 foundations of personal finance  30750
  15                        personal loan with cosigner  30750
  16                          personal finance textbook  30750
  17                                       snap finance  30750
  18                           radical personal finance  30550
  19                               msn personal finance  30550
  20  susan took out a personal loan for $3,500 at a...  30550
  21                         personal finance for teens  30550
  22                              personal finance book    200
  23                              personal finance jobs    200
  24                               personal finance lab    170},
 'virtual cards': {'top':                                    query  value
  0                           virtual card    100
  1                           credit cards     91
  2                   virtual credit cards     71
  3                    virtual credit card     50
  4                     virtual gift cards     50
  5                             gift cards     50
  6                 virtual birthday cards     36
  7                     virtual cards free     36
  8                      virtual gift card     29
  9            virtual birthday cards free     14
  10  instant approval virtual credit card     14
  11         instant approval credit cards     14
  12           instant virtual credit card     14
  13                  virtual cards online     14
  14               virtual visa gift cards     14
  15                     virtual visa card     14
  16                                  visa     14
  17                     online gift cards     14
  18                virtual business cards      7
  19                        business cards      7
  20                        visa gift card      7
  21                virtual visa gift card      7
  22             virtual gift cards online      7
  23                 virtual payment cards      7
  24                    virtual debit card      7,
  'rising':                    query   value
  0  virtual payment cards  152250
  1   virtual prepaid card  152200
  2           click to pay  148700
  3            e gift card  148700
  4                 ecards  148700
  5  buy gift cards online  148700
  6          prepaid cards  148700},
 'digital wallet': {'top':                                 query  value
  0                       crypto wallet    100
  1               digital wallet crypto    100
  2                     digital wallets    100
  3                 best digital wallet    100
  4               paypal digital wallet    100
  5              what is digital wallet    100
  6      bank of america digital wallet     67
  7           how to use digital wallet     67
  8                   my digital wallet     67
  9                chase digital wallet     67
  10              google digital wallet     67
  11                      google wallet     67
  12           what is a digital wallet     67
  13               apple digital wallet     67
  14                       apple wallet     67
  15                 digital wallet app     67
  16          prepaid digital solutions     33
  17             prepaid digital wallet     33
  18                         google pay     33
  19             android digital wallet     33
  20        how to get a digital wallet     33
  21  digital wallet for cryptocurrency     33
  22                     google pay app     32
  23                         wax wallet     32,
  'rising':                                query   value
  0                    digital wallets  367500
  1          prepaid digital solutions  122450
  2             android digital wallet  122450
  3  digital wallet for cryptocurrency  122450
  4                     google pay app  118100
  5                         wax wallet  118100
  6     bank of america digital wallet     130
  7           what is a digital wallet     130
  8              paypal digital wallet      70},
 'financial planning': {'top':                                 query  value
  0          what is financial planning    100
  1         personal financial planning     68
  2         business financial planning     57
  3          financial planning advisor     56
  4                   financial advisor     56
  5                 retirement planning     48
  6       retirement financial planning     47
  7         financial planning services     44
  8                   financial planner     44
  9          financial planning near me     38
  10         financial planning process     35
  11       financial planning insurance     27
  12    financial planning and analysis     26
  13                    estate planning     26
  14       strategic financial planning     26
  15        financial planning software     26
  16      financial planning definition     26
  17          financial planning salary     24
  18     college for financial planning     24
  19         college financial planning     24
  20            financial planning help     21
  21  financial planning for retirement     21
  22       financial planning companies     21
  23            financial planning jobs     21
  24        types of financial planning     18,
  'rising':                                                 query   value
  0                 why is financial planning important  128350
  1                                   creative planning   97850
  2                       financial planning calculator   96250
  3                        best financial planning apps   65200
  4                          divorce financial planning   65200
  5                                   cell phone stores   64600
  6                        financial planner definition   64600
  7              personal financial planning definition   64100
  8   planning to finance higher education helps peo...   64100
  9   planning to finance higher education helps peo...   64100
  10                     financial planning minneapolis   32550
  11                      masters in financial planning   32550
  12                      center for financial planning   32550
  13               key components of financial planning   32550
  14                           financial planning books   32550
  15  which would be most helpful when considering a...   32550
  16                         financial planning seattle   32250
  17  what inventory management procedure helps a fi...   32250
  18  what are the main purposes of a budget? select...   32250
  19                  foundation for financial planning   32000
  20                         financial planning near me    1000
  21                      financial planning definition     650
  22                            financial planning tool     400
  23                 risk management financial planning     150
  24                                retirement planning      50}}

In [10]:
#Access the data from the nested dictionary and print the top 20 related queries. Rename the columns by using the .rename(columns= {}) function
data = pytrends.related_queries()
kw1 = pd.DataFrame.from_dict(data['investment management']['top'][:20]).rename(columns = {"query": "Investment Management Related", "value":"Top Value"})
kw2 = pd.DataFrame.from_dict(data['personal finance']['top'][:20]).rename(columns = {"query": "Personal Finance Related", "value":"Top Value"})
kw3 = pd.DataFrame.from_dict(data['virtual cards']['top'][:20]).rename(columns = {"query": "Virtual Cards Related", "value":"Top Value"})
kw4 = pd.DataFrame.from_dict(data['digital wallet']['top'][:20]).rename(columns = {"query": "Digital Wallet Related", "value":"Top Value"})
kw5 = pd.DataFrame.from_dict(data['financial planning']['top'][:20]).rename(columns = {"query": "Financial Planning Related", "value":"Top Value"})

print(kw1)
print(kw2)
print(kw3)
print(kw4)
print(kw5)

           Investment Management Related  Top Value
0          investment management company        100
1          what is investment management         74
2                       asset management         63
3           wealth investment management         55
4                      wealth management         55
5             investment management fees         52
6             investment management firm         44
7                        investment bank         41
8      real estate investment management         41
9                   return on investment         37
10                      money management         37
11                   property management         33
12            investment risk management         33
13        investment property management         30
14       investment management companies         30
15                  investment companies         29
16            investment management jobs         26
17                    investment advisor         26
18        investment management services         26
19  morgan stanley investment management         18
       Personal Finance Related  Top Value
0      what is personal finance        100
1       reddit personal finance         91
2                 personal loan         88
3                          loan         88
4         personal loan finance         88
5                personal loans         62
6        personal finance loans         62
7                         money         56
8      personal finance quizlet         47
9          personal finance app         38
10    personal finance software         24
11  personal finance management         24
12      personal finance budget         23
13     personal finance company         21
14        personal finance book         21
15   personal finance education         21
16        personal finance jobs         21
17      personal finance course         18
18                yahoo finance         18
19       yahoo personal finance         18
                   Virtual Cards Related  Top Value
0                           virtual card        100
1                           credit cards         91
2                   virtual credit cards         71
3                    virtual credit card         50
4                     virtual gift cards         50
5                             gift cards         50
6                 virtual birthday cards         36
7                     virtual cards free         36
8                      virtual gift card         29
9            virtual birthday cards free         14
10  instant approval virtual credit card         14
11         instant approval credit cards         14
12           instant virtual credit card         14
13                  virtual cards online         14
14               virtual visa gift cards         14
15                     virtual visa card         14
16                                  visa         14
17                     online gift cards         14
18                virtual business cards          7
19                        business cards          7
            Digital Wallet Related  Top Value
0                    crypto wallet        100
1            digital wallet crypto        100
2                  digital wallets        100
3              best digital wallet        100
4            paypal digital wallet        100
5           what is digital wallet        100
6   bank of america digital wallet         67
7        how to use digital wallet         67
8                my digital wallet         67
9             chase digital wallet         67
10           google digital wallet         67
11                   google wallet         67
12        what is a digital wallet         67
13            apple digital wallet         67
14                    apple wallet         67
15              digital wallet app         67
16       prepaid digital solutions         33
17          prepaid digital wallet         33
18                      google pay         33
19          android digital wallet         33
         Financial Planning Related  Top Value
0        what is financial planning        100
1       personal financial planning         68
2       business financial planning         57
3        financial planning advisor         56
4                 financial advisor         56
5               retirement planning         48
6     retirement financial planning         47
7       financial planning services         44
8                 financial planner         44
9        financial planning near me         38
10       financial planning process         35
11     financial planning insurance         27
12  financial planning and analysis         26
13                  estate planning         26
14     strategic financial planning         26
15      financial planning software         26
16    financial planning definition         26
17        financial planning salary         24
18   college for financial planning         24
19       college financial planning         24

# Export Data Into Excel Sheets

In [11]:
# Import xlwt, ExcelWriter, and xlsxwriter to turn dataframes into excel files for time series modeling and Tableau graphs
import xlwt
from xlwt.Workbook import *
from pandas import ExcelWriter
import xlsxwriter

In [12]:
# Create an excel sheet with multiple sheets for the Related Queries dataframes and call the file 'Related Queries'

writer = pd.ExcelWriter('Related Queries.xlsx', engine='xlsxwriter')

kw1.to_excel(writer, sheet_name='Investment')

kw2.to_excel(writer, sheet_name='Personal Fin')

kw3.to_excel(writer, sheet_name='Virtual Card')

kw4.to_excel(writer, sheet_name='Digital Wallet')

kw5.to_excel(writer, sheet_name='Financial Plan')

writer.save()

In [13]:
# Create an excel sheet for Keyword Interest Weekly and call it 'Weekly Keyword Interest'
writer1 = pd.ExcelWriter('Weekly Keyword Interest.xlsx', engine='xlsxwriter')

keyword_interest.to_excel(writer1, sheet_name='Weekly')

writer1.save()

In [14]:
# Create an excel sheet for Hourly Historical Keyword Interest and call it 'Hourly Keyword Interest'
writer2 = pd.ExcelWriter('Hourly Keyword Interest.xlsx', engine='xlsxwriter')

kw_hist_interest.to_excel(writer2, sheet_name='Hourly')

writer2.save()

In [15]:
# Create an excel sheet for Merged Regional Keyword Interest and call it 'Regional Keyword Interest'
writer3 = pd.ExcelWriter('Regional Keyword Interest.xlsx', engine='xlsxwriter')

merged_kw_region.to_excel(writer3, sheet_name='By State')

writer3.save()

In [16]:
# Create a master excel file with all the dataframes on different sheets for stakeholders so that they can interact with the data. Call this file 'Master Copy'

writer4 = pd.ExcelWriter('Master Copy.xlsx', engine='xlsxwriter')

kw1.to_excel(writer4, sheet_name='Investment')

kw2.to_excel(writer4, sheet_name='Personal Fin')

kw3.to_excel(writer4, sheet_name='Virtual Card')

kw4.to_excel(writer4, sheet_name='Digital Wallet')

kw5.to_excel(writer4, sheet_name='Financial Plan')

keyword_interest.to_excel(writer4, sheet_name='Weekly')

kw_hist_interest.to_excel(writer4, sheet_name='Hourly')

merged_kw_region.to_excel(writer4, sheet_name='By State')

writer4.save()